### ISSUE TITLE
Misc Production Changes

### ISSUE THREAD

**Issue by dternyak** [MyCryptoHQ/MyCrypto#1732]
### TODOs

* [ ] Link to published blog post about the launch
* [ ] Setup `https://legacy.mycrypto.com` (cc @skubakdj)
    * Also make sure `https://legacy.mycrypto.com/helpers` still works too
* [ ] Get copy approved by Jordan
* [ ] (Maybe) Get a better welcome modal image / banner

from https://github.com/MyCryptoHQ/MyCrypto/pull/1673
