### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by james-prado** [MyCryptoHQ/MyCrypto#519]
A list of all `TODO` & `FIXME` comments in the repo

- [ ] __Blocking:__ Communicate invalid file to user  – [Keystore.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/components/WalletDecrypt/Keystore.tsx#L16)
- [x] __Blocking:__ Throw error if ABI is malformed, related to https://github.com/MyEtherWallet/MyEtherWallet/issues/272  – [contract.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/contract.ts#L35)
- [x] __Blocking:__ Check that eth balance is not lesser than txAmount + gasCost  – [transaction.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/transaction.ts#L122)
- [ ] __Blocking:__ Update error handling, related to https://github.com/MyEtherWallet/MyEtherWallet/issues/272  – [orders.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/sagas/swap/orders.ts#L98)
- [x] __Blocking:__ Update error messages, related to https://github.com/MyEtherWallet/MyEtherWallet/issues/272 (1/2)  – [wallet.tsx](https://github.com/MyEtherWallet/MyEtherWalop/common/sagas/wallet.tsx#L123)
- [ ] __Blocking:__ Update error messages, related to https://github.com/MyEtherWallet/MyEtherWallet/issues/272 (2/2) – [wallet.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/sagas/wallet.tsx#L134)
- [ ] __Blocking:__ Stop polling / show notifications based on order status  – [orders.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/sagas/swap/orders.ts#L139)
- [x] __Blocking:__ Handle Errors – [sagas/wallet.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/sagas/wallet.tsx#L69)
- [x] Update types  – [Root.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/Root.tsx#L16)
- [x] Update types  – [TokenRow.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/components/BalanceSidebar/TokenBalances/TokenRow.tsx#L57)
- [ ] Add Types for Vendor Files  – [Trezor.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/components/WalletDecrypt/Trezor.tsx#L94)
- [x]  Update types  – [AccountInfo.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/components/BalanceSidebar/AccountInfo.tsx#L40)
- [x] Update type to an array of BNs  – [contract.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/contract.ts#L27)
- [x] Update return type to an array of BNs  – [contract.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/contract.ts#L92)
- [ ] Support events, constructors, fallbacks, array slots, types  – [contract.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/contract.ts#L1)
- [ ] Internationalize  – [actionPayloads.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/actions/rates/actionPayloads.ts#L4)
- [ ] Typescript bug: https://github.com/Microsoft/TypeScript/issues/13948  – [AddCustomTokenForm.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/components/BalanceSidebar/TokenBalances/AddCustomTokenForm.tsx#L103)
- [x] ~Don't hardcode link  – [GasPriceDropdown.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/components/Header/components/GasPriceDropdown.tsx#L64)~ Closed by https://github.com/MyEtherWallet/MyEtherWallet/pull/533
- [ ] Use reusable components with validation  – [InteractExplorer/index.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/containers/Tabs/Contracts/components/Interact/components/InteractExplorer/index.tsx#L94)
- [x]  common components for address, abi json && Don't hardcode donation address in `placeholder={...}`  – [InteractForm/index.tsx](https://github.com/MyEtherWalletherWallet/blob/develop/common/containers/Tabs/Contracts/components/Interact/components/InteractForm/index.tsx#L65)
- [x] Listen to gas price changes, debounce the call, and handle gas estimation  – [SendTransaction/index.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/containers/Tabs/SendTransaction/index.tsx#L163)
- [ ] Update pattern to scale beyond BTC, ETH, and REP  – [ReceivingAddress.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/containers/Tabs/Swap/components/ReceivingAddress.tsx#L56)
- [x] `TODO: caching`  – [contracts/index.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/contracts/index.ts#L87)
- [x] `TODO: pass object instead`  – [contracts/index.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/contracts/index.ts#L133)
- [ ] Parse checksummed addresses (1/2)  – [ABIFunction.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/contracts/ABIFunction.ts#L99)
- [ ] Parse checksummed addresses (2/2) – [ABIFunction.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/contracts/ABIFunction.ts#L123)
- [ ] `//TODO: do this in O(n)` – [ABIFunction.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/contracts/ABIFunction.ts#L136)
- [ ] Introduce typechecking and typecasting mapping for inputs – [ABIFunction.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/contracts/ABIFunction.ts#L166)
- [ ] parse args based on type – [ABIFunction.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/contracts/ABIFunction.ts#L183)
- [ ] Explain what's going on here  – [signing.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/signing.ts#L47)
- [x] Use a pure function (don't mutate args)  – [values.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/values.ts#L18)
- [ ] Use a regex to detect proper paths  – [validators.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/validators.ts#L173)
- [x] Make the gaslimit dynamic (the limit shifts)  – [transaction.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/transaction.ts#L151)
- [x] Determine best place for helper function  – [transaction.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/transaction.ts#L303)
- [ ] Explain what's going on here & add tests, adapted from: [v3.10.2.6/app/scripts/uiFuncs.js](https://github.com/kvhnuke/etherwallet/blob/v3.10.2.6/app/scripts/uiFuncs.js#L24)  – [trezor.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/wallet/deterministic/trezor.ts#L30)
- [x] Remove this interface from [transaction](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/transaction.ts#L5), it's only for estimating gas costs  – [messages.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/messages.ts#L1)
- [ ] Make a library for error messages, related to https://github.com/MyEtherWallet/MyEtherWallet/issues/272 – [rates.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/reducers/rates.ts#L29)
- [x] Update naming  – [swap/index.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/reducers/swap/index.ts#L153)
- [ ] Implement request cancel – [orders.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/sagas/swap/orders.ts#L66)
- [ ] Add comments to clarify (1/4) – [formatters.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/utils/formatters.ts#L75)
- [ ]  Add comments to clarify (2/4) – [formatters.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/utils/formatters.ts#L87)
- [ ]  Add comments to clarify (3/4) – [formatters.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/utils/formatters.ts#L88)
- [ ]  Add comments to clarify (4/4) – [formatters.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/utils/formatters.ts#L89)
- [ ]  `$keyof?` – [config/actionTypes.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/actions/config/actionTypes.ts#L23)
- [x]  __Blocking:__ Breaks on failed checksums – [Identicon.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/components/ui/Identicon.tsx#L12)
- [ ]  Store limited amount if history – [QRCode.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/components/ui/QRCode.tsx#L4)
- [x]  Update Types – [WalletDecrypt/index.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/components/WalletDecrypt/index.tsx#L96)
- [x]  Update type to union type of actual steps – [GenerateWallet/index.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/containers/tabs/GenerateWallet/index.tsx#L21)
- [x]  Debounce – [AddressField.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/containers/tabs/SendTransaction/components/AddressField.tsx#L59)
- [ ]  Move to config – [Donate.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/containers/tabs/SendTransaction/components/Donate.tsx#L33)
- [x]  Update Type – [TabSection/index.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/containers/TabSection/index.tsx#L42)
- [ ]  Do checksum checks sideways – [validators.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/validators.ts#L74)
- [ ]  Unsure how to specify reduction context – [bn.d.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/typescript/bn.d.ts#L32)
- [ ]  Pick a less magic number – [derivationChecker.int.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/spec/integration/derivationChecker.int.ts#L5)

Vague:
- [ ]  FIXME – [config.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/reducers/config.ts#L25)
- [ ]  FIXME – [sagas/notifications.ts](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/sagas/notifications.ts#L17)
- [ ]  FIXME – [PrintElement.tsx](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/utils/PrintElement.tsx#L44)

## Templates:
- [ ]  Title – [file](https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/)
__Blocking:__

**Comment by wbobeirne** [comment]
The remaining ones marked blocking are just about error messages / user display, and many of these have been addressed via refactors. Should we unmark this task as blocking, and just tackle TODOs as we come across them?

**Comment by dternyak** [comment]
Yes, agreed.

**Comment by james-prado** [comment]
Closing stale issue
